/*
 * Copyright (C) 2006-2018 Talend Inc. - www.talend.com
 * 
 * This source code is available under agreement available at
 * %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
 * 
 * You should have received a copy of the agreement along with this program; if not, write to Talend SA 9 rue Pages
 * 92150 Suresnes, France
 */

package org.talend.mdm.commmon.metadata;

/**
 *
 */
public enum ValidationError {
    XML_SCHEMA,
    ENTITY_CANNOT_USE_ABSTRACT_REUSABLE_TYPE,
    ENTITY_CANNOT_INHERIT_FROM_REUSABLE_TYPE,
    FIELD_KEY_CANNOT_BE_REPEATABLE,
    FIELD_KEY_MUST_BE_MANDATORY,
    FOREIGN_KEY_NOT_STRING_TYPED,
    MULTIPLE_INHERITANCE_NOT_ALLOWED,
    PRIMARY_KEY_INFO_NOT_IN_ENTITY,
    PRIMARY_KEY_INFO_CANNOT_BE_REPEATABLE,
    TYPE_INVALID_NAME,
    TYPE_DOES_NOT_EXIST,
    TYPE_DOES_NOT_OWN_FIELD,
    TYPE_DOES_NOT_OWN_KEY,
    LOOKUP_FIELD_NOT_IN_ENTITY,
    LOOKUP_FIELD_CANNOT_BE_KEY,
    LOOKUP_FIELD_MUST_BE_SIMPLE_TYPE,
    PRIMARY_KEY_INFO_TYPE_NOT_PRIMITIVE,
    TYPE_CANNOT_OVERRIDE_SUPER_TYPE_KEY,
    FOREIGN_KEY_INFO_REPEATABLE,
    FIELD_KEY_CANNOT_BE_FOREIGN_KEY,
    FOREIGN_KEY_INFO_NOT_PRIMITIVE_XSD_TYPED,
    FOREIGN_KEY_INFO_NOT_REFERENCING_FK_TYPE,
    FOREIGN_KEY_SHOULD_POINT_TO_PRIMARY_KEY,
    FOREIGN_KEY_USES_MAX_LENGTH,
    FOREIGN_KEY_INFO_INVALID,
    FOREIGN_KEY_HOST_INVALID,
    TYPE_USE_XSD_ATTRIBUTES,
    CIRCULAR_DEPENDENCY,
    UNUSED_REUSABLE_TYPE,
    MANDATORY_FIELD_MAY_NOT_BE_VISIBLE,
    FIELD_CANNOT_OVERRIDE_INHERITED_ELEMENT,
    UNCAUGHT_ERROR,
    PERMISSION_SYSTEM_ROLE_NOT_SETTABLE,
    INHERITANCE_TYPE_CANNOT_INCLUDE_CIRCLE_FIELD
}
